---
- name: Configure AAP for Winburgia Windows Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aap_configuration_dispatcher_roles:
      - role: controller_credential_types
        var: controller_credential_types
        tags: credential_types
      - role: controller_credentials
        var: controller_credentials
        tags: credentials
      - role: controller_projects
        var: controller_projects
        tags: projects
      - role: controller_inventories
        var: controller_inventories
        tags: inventories
      - role: controller_inventory_sources
        var: controller_inventory_sources
        tags: inventory_sources
      - role: controller_hosts
        var: controller_hosts
        tags: hosts
      - role: controller_execution_environments
        var: controller_execution_environments
        tags: execution_environments
      - role: controller_job_templates
        var: controller_templates
        tags: job_templates
      - role: controller_workflow_job_templates
        var: controller_workflows
        tags: workflow_job_templates

  pre_tasks:
    - name: Load config-as-code variables
      ansible.builtin.include_vars:
        dir: controller_config
        extensions:
          - yml

  roles:
    - infra.aap_configuration.dispatch
