---
controller_credential_types:
  - name: Microsoft AD LDAP
    description: Credential for Microsoft Active Directory LDAP inventory plugin
    kind: cloud
    inputs:
      fields:
        - type: string
          id: ad_server
          label: AD Server
        - type: string
          id: ad_username
          label: AD Username
        - type: string
          id: ad_password
          label: AD Password
          secret: true
      required:
        - ad_server
        - ad_username
        - ad_password
    injectors:
      env:
        MICROSOFT_AD_LDAP_SERVER: !unsafe "{{ ad_server }}"
        MICROSOFT_AD_LDAP_USERNAME: !unsafe "{{ ad_username }}"
        MICROSOFT_AD_LDAP_PASSWORD: !unsafe "{{ ad_password }}"
